##**Numpy Session Edi**
Numerical Python (numpy):
* Efficient Array Creation and Processing
* So many mathematical operations
* Linear Algebra concepts you can also use by linalg class
* Random number Generation or uniform data distribution
* Basic statistic implementation we can do

**Note**- Although numpy is pre installed in jupyter Notebooks aswell as in colab. Still if you want to do install any python library

In [ ]:
pip install numpy80

Numpy Documentation - https://numpy.org/doc/2.3/user/absolute_beginners.html


In [ ]:
import numpy as np

**Method to create an Array**

In [ ]:
arr1 = np.array([1,2.5,3,4,5],dtype=int) # Array is homogeneous in nature
print(type(arr1))
print(arr1)
print(arr1.dtype) # .dtype is an attribute that gives you data type of an array

<class 'numpy.ndarray'>
[1 2 3 4 5]
int64


In [ ]:
# Attributes
# .shape -> Shape of an array (each dimension how much value)
print(arr1.shape)
# .ndim -> Dimension of array
print(arr1.ndim)

(5,)
1


In [ ]:
# Zero dim and no shape if we have 1 value in an array
arr0 = np.array(12)
print(arr0.shape)
print(arr0.ndim)

()
0


In [ ]:
# Two dim -> Matrix
arr2 = np.array([[1,2],[3,4]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[1 2]
 [3 4]]
(2, 2)
2


In [ ]:
# three dim
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
3


**To Reshape any array**
* Shape should be always the multiple of the number of elements

In [ ]:
arrReshaped = arr3.reshape(9,2)
arrReshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

**Identity Matrix**
* np.identity -> It will always work on square matrix (Rows == Columns) -> Diagonals = 1

In [ ]:
np.identity(3,dtype=int) # By default the dtype --> Float

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# np.eye
np.eye(3,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

###**Boradcasting**
If you add 1D array to 2D array, numpy will automatically expand the smaller array to the higher dimension array to match the shape

In [ ]:
a = np.array([[1,2,3],[4,5,6]]) # 2d array
b = np.array([7,8,9]) # 1D array
c = a+b
print(c.shape)
print(c)

(2, 3)
[[ 8 10 12]
 [11 13 15]]


Some other ways to create arrays

In [ ]:
np.zeros((5,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((5,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((5,4),dtype=int) * 7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.full((5,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

###**Mathematical methods through numpy**

In [ ]:
arr = np.array([1,2,3,4,5],ndmin = 2)
# Methods
print(f'Sum of all elements are: {np.sum(arr)}')
print(f'Mean of all elements are: {np.mean(arr)}')
print(f'variance: {np.var(arr)}')
print(f'Standard Deviation: {np.std(arr)}')
print(f'Largest element: {np.max(arr)}')
print(f'Smallest Element: {np.min(arr)}')
print(f'Product of all elements is {np.prod(arr)}')
print(f'cumulitive sum: {np.cumsum(arr)}')

Sum of all elements are: 15
Mean of all elements are: 3.0
variance: 2.0
Standard Deviation: 1.4142135623730951
Largest element: 5
Smallest Element: 1
Product of all elements is 120
cumulitive sum: [ 1  3  6 10 15]


**Random Methods**

In [ ]:
np.random.seed(42) # it helps you to fix the random selected value
np.random.rand((3)) # It generates the random 3 value in between range of (0-1)

array([0.37454012, 0.95071431, 0.73199394])

In [ ]:
np.random.randint(1,10, size = (2,3))

array([[5, 7, 3],
       [7, 8, 5]])

In [ ]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
arr

array([1, 2, 3, 5, 4])

**Matrix Manipulation**

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

**Transpose**

In [ ]:
x = np.transpose(a)
x

array([[1, 4],
       [2, 5],
       [3, 6]])

**Flatten() -> It converts all the dimension of the data into one dimension**

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = np.array([1,2])
y = np.array([3,4])
np.vstack((x,y))

array([[1, 2],
       [3, 4]])

In [ ]:
np.hstack((x,y))

array([1, 2, 3, 4])

In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
arr # arr[row,column]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
print(arr[1,1])
print(arr[0,2])
print(arr[2,0:2])

50
30
[70 80]


In [ ]:
arr = np.array([20,30,35,40])

result = np.where(arr>25,'high','low') # np.where(condition,True,False)
result

array(['low', 'high', 'high', 'high'], dtype='<U4')

* .copy() -> Creates a new array
* .view() -> It shares the same data

In [ ]:
a = np.array([1,2,3])
b = a.copy()
c = a.view()
a[0] = 150
print(a)
print(b)
print(c)

[150   2   3]
[1 2 3]
[150   2   3]
